title: '2020'
baseurl: /
permalink: '/:title/'
layout_style: overflow
header:
  bg: dark
  has_nav: true
  has_social: true
  profile_img: /images/20191130_212104.jpg
  tagline: ...
  title: 2020 journal
footer:
  content: '&copy; All rights reserved.'
  links:
    - new_window: true
      text: Made with Stackbit (and hope)
      url: 'https://www.stackbit.com'
sass:
  indentWidth: 4
  precision: 10
  style: nested
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
